# Generated by Django 4.2.1 on 2023-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='descr',
            field=models.CharField(max_length=50, verbose_name='Описание акции'),
        ),
    ]
