# Generated by Django 4.2.1 on 2023-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_course_alter_stock_descr_courseitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseitem",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
