# Generated by Django 4.2.1 on 2023-05-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_courseitem_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseitem",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_items",
                to="api.course",
            ),
        ),
    ]
